feat: Separa os testes unitários dos testes de integração

diff --git a/.github/workflows/workflow-ci.yml b/.github/workflows/workflow-ci.yml
--- a/.github/workflows/workflow-ci.yml
+++ b/.github/workflows/workflow-ci.yml
@@ -30,7 +30,6 @@ jobs:
             exit 1
           else
             echo >&2 "Valid commit message."
-          fi
 
   build:
     runs-on: ubuntu-latest
@@ -49,7 +48,7 @@ jobs:
             exit 1
           fi
 
-  test:
+  unit-test:
     runs-on: ubuntu-latest
     needs: build
     steps:
@@ -58,26 +57,44 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-      - name: Run the Maven verify phase
+      - name: Run unit tests
+        run: |
+          mvn --batch-mode --update-snapshots test -f projetoA3/pom.xml
+          if [ $? -ne 0 ]; then
+            echo "Unit test phase failed. Por favor cheque as suas mudanças e tente novamente."
+            exit 1
+          fi
+
+  integration-test:
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.ref == 'refs/heads/release'
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+      - name: Run integration tests
         run: |
           mvn --batch-mode --update-snapshots verify -f projetoA3/pom.xml
           if [ $? -ne 0 ]; then
-            echo "Test phase failed. Por favor cheque as suas mudanças e tente novamente."
+            echo "Integration test phase failed. Por favor cheque as suas mudanças e tente novamente."
             exit 1
           fi
       - name: Upload ftp
         uses: sebastianpopp/ftp-action@releases/v2
         with:
-          host: joaobsjunior.com.br
-          user: aluno-ftp
-          password: a1b2c3d4@
+          host: ${{ secrets.FTP_HOST }}
+          user: ${{ secrets.FTP_USER }}
+          password: ${{ secrets.FTP_PASSWORD }}
           localDir: /home/runner/work/A3-Gestao-de-Software/A3-Gestao-de-Software/projetoA3/target/site/jacoco
           remoteDir: A3-Gestao-de-Software
 
   release:
     runs-on: ubuntu-latest
-    needs: test
-    if: github.ref == 'refs/heads/release'  # Condição para acionar apenas na branch 'release'
+    needs: integration-test
+    if: github.ref == 'refs/heads/main'
     steps:
       - name: Install semantic-release
         run: npm install -g semantic-release@17 @semantic-release/git@10
