feat(test): Adiciona sonarcloud 2

diff --git a/.github/workflows/workflow-ci.yml b/.github/workflows/workflow-ci.yml
--- a/.github/workflows/workflow-ci.yml
+++ b/.github/workflows/workflow-ci.yml
@@ -31,6 +31,7 @@ jobs:
           else
             echo >&2 "Valid commit message."
           fi
+  
 
   build:
     runs-on: ubuntu-latest
@@ -66,12 +67,36 @@ jobs:
             exit 1
           fi
 
+  integration-test:
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.ref == 'refs/heads/release'
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+      - name: Run integration tests
+        run: |
+          mvn --batch-mode --update-snapshots verify -f projetoA3/pom.xml
+          if [ $? -ne 0 ]; then
+            echo "Integration test phase failed. Por favor cheque as suas mudanças e tente novamente."
+            exit 1
+          fi
+      - name: Upload ftp
+        uses: sebastianpopp/ftp-action@releases/v2
+        with:
+          host: ${{ secrets.FTP_HOST }}
+          user: ${{ secrets.FTP_USER }}
+          password: ${{ secrets.FTP_PASSWORD }}
+          localDir: /home/runner/work/A3-Gestao-de-Software/A3-Gestao-de-Software/projetoA3/target/site/jacoco
+          remoteDir: A3-Gestao-de-Software
+
 
   release:
     runs-on: ubuntu-latest
-    needs:
-      - integration-test
-      - sonarcloud-analysis
+    needs: integration-test
     if: github.ref == 'refs/heads/main'
     steps:
       - name: Install semantic-release
