Update workflow-ci.yml

diff --git a/.github/workflows/workflow-ci.yml b/.github/workflows/workflow-ci.yml
--- a/.github/workflows/workflow-ci.yml
+++ b/.github/workflows/workflow-ci.yml
@@ -18,6 +18,21 @@ jobs:
           distribution: 'temurin'
           architecture: x64
           cache: maven
+      - name: Validate Commit Message
+        run: |
+          # Regex to validate the type pattern
+          REGEX="^((Merge[ a-z-]* branch.)|(Revert)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.\))?!?: .))"
+          
+          COMMIT_MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA)
+          
+          echo "Commit Message: ${COMMIT_MESSAGE}"
+          
+          if ! [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
+            echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard."
+            exit 1
+          else
+            echo >&2 "Valid commit message."
+          fi
 
 
   build:
@@ -33,8 +48,8 @@ jobs:
         run:  |
           mvn -B package -f A3_Gestao/ProjetoA3/A3/pom.xml
           if [ $? -ne 0 ]; then
-          echo "Build failed. Por favor cheque as suas mudanças e tente novamente."
-          exit 1
+            echo "Build failed. Por favor cheque as suas mudanças e tente novamente."
+            exit 1
           fi
   
   test:
@@ -50,6 +65,6 @@ jobs:
         run: |
           mvn --batch-mode --update-snapshots verify -f A3_Gestao/ProjetoA3/A3/pom.xml
           if [ $? -ne 0 ]; then
-          echo "Build failed. Por favor cheque as suas mudanças e tente novamente."
-          exit 1
+            echo "Build failed. Por favor cheque as suas mudanças e tente novamente."
+            exit 1
           fi
